services:
  - type: web
    name: steam-giveaway-bot
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: "8389691438:AAGyEfUjmiDFYjmtSRjPtnLCiB-JDZvgPpw"
      - key: ADMIN_ID
        value: "7073433113"
